/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#6d3bd7',
        'on-secondary': '#233144',
        'inverse-on-surface': '#283044',
        'on-error-container': '#ffdad6',
        'surface-dim': '#0b1326',
        'primary-fixed': '#e9ddff',
        'on-secondary-fixed': '#0d1c2f',
        'inverse-surface': '#dae2fd',
        'primary-fixed-dim': '#d0bcff',
        'on-secondary-fixed-variant': '#3a485c',
        'outline': '#958ea0',
        'tertiary-fixed': '#ffd9e4',
        'on-tertiary-fixed-variant': '#8c0053',
        'tertiary-fixed-dim': '#ffb0cd',
        'surface': '#0b1326',
        'on-background': '#dae2fd',
        'tertiary': '#ffb0cd',
        'surface-bright': '#31394d',
        'secondary-fixed': '#d5e3fd',
        'secondary': '#b9c7e0',
        'surface-container-highest': '#2d3449',
        'error': '#ffb4ab',
        'primary': '#d0bcff',
        'on-primary-container': '#340080',
        'surface-container-high': '#222a3d',
        'surface-container-lowest': '#060e20',
        'on-surface-variant': '#cbc3d7',
        'tertiary-container': '#f751a1',
        'surface-container-low': '#131b2e',
        'background': '#0b1326',
        'on-tertiary-container': '#570032',
        'error-container': '#93000a',
        'on-tertiary': '#640039',
        'surface-tint': '#d0bcff',
        'secondary-container': '#3c4a5e',
        'outline-variant': '#494454',
        'on-primary': '#3c0091',
        'surface-container': '#171f33',
        'on-primary-fixed': '#23005c',
        'on-tertiary-fixed': '#3e0022',
        'secondary-fixed-dim': '#b9c7e0',
        'on-primary-fixed-variant': '#5516be',
        'surface-variant': '#2d3449',
        'on-secondary-container': '#abb9d2',
        'primary-container': '#a078ff',
        'on-surface': '#dae2fd',
        'on-error': '#690005',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans'],
        'body': ['Inter'],
        'label': ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
