name: musicparty
description: "MusicParty - Votá las canciones en eventos en vivo. Escaneá el QR, elegí tus favoritas y hacé que suenen."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  uuid: ^4.5.3
  shared_preferences: ^2.5.4
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
